/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oop_projeck_oficial;

import java.awt.BorderLayout;
import java.util.HashMap;
import javax.swing.DefaultListModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.time.TimeSeriesCollection;
import org.jfree.data.xy.XYDataset;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author zuzab
 */
public class Control extends javax.swing.JFrame {
    private HashMap <String, Asset> hashMapAsset;
    DefaultListModel listModel = new DefaultListModel();

    /**
     * Creates new form COS_OFICJALNEGO
     */
    public Control() {
        initComponents();
    
    nCom.setText(Integer.toString(MainWorld.noCommodity));
    nCompany.setText(Integer.toString(MainWorld.noCompany));
    nCur.setText(Integer.toString(MainWorld.noCurrency));
    nCurM.setText(Integer.toString(MainWorld.noCurrencyMarkets));
    nFund.setText(Integer.toString(MainWorld.noFund));
    nInd.setText(Integer.toString(MainWorld.noIndex));
    nInv.setText(Integer.toString(MainWorld.noInvestor));
    nStock.setText(Integer.toString(MainWorld.noCompany));
    nStockM.setText(Integer.toString(MainWorld.noStockMarkets));
    nComM.setText(Integer.toString(MainWorld.noCommodityMarkets));
    hashMapAsset = new HashMap<>();
     for (int i = 0;i<MainWorld.listOfCompanies.size();i++){
       jComboBox1Company.addItem(MainWorld.listOfCompanies.get(i).getName());
       jComboBox1Company1.addItem(MainWorld.listOfCompanies.get(i).getName());
     }
      
   
    for (int i = 0;i<MainWorld.listOfAssets.size();i++){
        hashMapAsset.put(MainWorld.listOfAssets.get(i).getName(), MainWorld.listOfAssets.get(i));
        listModel.addElement(MainWorld.listOfAssets.get(i).getName());
        
        if (MainWorld.listOfAssets.get(i).getType()=="Stock"){
            jComboBox1Stock.addItem(MainWorld.listOfAssets.get(i).getName());
        }
        if (MainWorld.listOfAssets.get(i).getType()=="Commodity"){
            jComboBox2Commodity.addItem(MainWorld.listOfAssets.get(i).getName());
        }
        if(MainWorld.listOfAssets.get(i).getType()=="Currency"){
            jComboBox3Currency.addItem(MainWorld.listOfAssets.get(i).getName());
        }
        this.listOfAssets.setModel( listModel );
    }
   for (int i =0;i<MainWorld.listOfTraders.size();i++){
        jComboBox1Investor.addItem(MainWorld.listOfTraders.get(i).getFirstName());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabGeneralText = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nStock = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nStockM = new javax.swing.JLabel();
        nInd = new javax.swing.JLabel();
        nCompany = new javax.swing.JLabel();
        nCom = new javax.swing.JLabel();
        nCur = new javax.swing.JLabel();
        nCurM = new javax.swing.JLabel();
        nComM = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        nInv = new javax.swing.JLabel();
        nFund = new javax.swing.JLabel();
        dStockM = new javax.swing.JButton();
        dodCurM = new javax.swing.JButton();
        dodStock = new javax.swing.JButton();
        dodCom = new javax.swing.JButton();
        dodCur = new javax.swing.JButton();
        dodInd = new javax.swing.JButton();
        dodCompany = new javax.swing.JButton();
        dodInv = new javax.swing.JButton();
        dodFund = new javax.swing.JButton();
        dodComM = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textPanelCreateSection = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        freq = new javax.swing.JLabel();
        speed = new javax.swing.JSlider();
        jPanel2 = new javax.swing.JPanel();
        jComboBox1Stock = new javax.swing.JComboBox<>();
        printcombo1 = new javax.swing.JButton();
        jComboBox2Commodity = new javax.swing.JComboBox<>();
        printcombo2 = new javax.swing.JButton();
        jComboBox3Currency = new javax.swing.JComboBox<>();
        printcombo3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowAsset = new javax.swing.JTextPane();
        graphPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listOfAssets = new javax.swing.JList<>();
        creatgraphbutton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1Company = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        beforeCompany = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        afterCompany = new javax.swing.JTextArea();
        noStocktoBuyOut = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1Company1 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        areaForCompany = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1Investor = new javax.swing.JComboBox<>();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextAreaInvestor = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Stock");

        jLabel6.setText("Commodity");

        jLabel7.setText("Currency");

        jLabel8.setText("Index");

        jLabel9.setText("Company");

        jLabel10.setText("Investor");

        jLabel11.setText("Funds");

        nStock.setText("nS");

        jLabel13.setText("Commodity Market");

        jLabel14.setText("Stock Market");

        nStockM.setText("nCM");

        nInd.setText("nInd");

        nCompany.setText("nCom");

        nCom.setText("nC");

        nCur.setText("nCr");

        nCurM.setText("nCrM");

        nComM.setText("nCM");

        jLabel32.setText("Currency Market");

        nInv.setText("nInv");

        nFund.setText("nF");

        dStockM.setText("Add new");
        dStockM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dStockMActionPerformed(evt);
            }
        });

        dodCurM.setText("Add new");
        dodCurM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodCurMActionPerformed(evt);
            }
        });

        dodStock.setText("Add new");
        dodStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodStockActionPerformed(evt);
            }
        });

        dodCom.setText("Add new");
        dodCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodComActionPerformed(evt);
            }
        });

        dodCur.setText("Add new");
        dodCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodCurActionPerformed(evt);
            }
        });

        dodInd.setText("Add new");
        dodInd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodIndActionPerformed(evt);
            }
        });

        dodCompany.setText("Add new");
        dodCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodCompanyActionPerformed(evt);
            }
        });

        dodInv.setText("Add new");
        dodInv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodInvActionPerformed(evt);
            }
        });

        dodFund.setText("Add new");
        dodFund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodFundActionPerformed(evt);
            }
        });

        dodComM.setText("Add new");
        dodComM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dodComMActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(textPanelCreateSection);

        jLabel1.setText("Here You can add object to Your World!");

        freq.setText("Increase frequency of purchases");

        speed.setMajorTickSpacing(100);
        speed.setMaximum(2000);
        speed.setMinimum(10);
        speed.setPaintTicks(true);
        speed.setPaintTrack(false);
        speed.setSnapToTicks(true);
        speed.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                speedMouseDragged(evt);
            }
        });
        speed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                speedMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodCompany))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nInd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodInd))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nCur, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodCur))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nStockM, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dStockM))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nFund, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodFund))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nInv, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodInv))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nComM, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodComM))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nCom, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodCom))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nStock, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodStock))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nCurM, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dodCurM))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(freq, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addGap(21, 21, 21)))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(freq, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(speed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nStockM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dStockM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nComM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dodComM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nCurM, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodCurM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nStock, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodStock))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nCom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodCom))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nCur, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodCur))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nInd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodInd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodCompany))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nInv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dodInv))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nFund, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dodFund)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addGap(60, 60, 60))
        );

        tabGeneralText.addTab("Creation", jPanel4);

        jComboBox1Stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1StockActionPerformed(evt);
            }
        });

        printcombo1.setText("Refresh");
        printcombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printcombo1ActionPerformed(evt);
            }
        });

        jComboBox2Commodity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2CommodityActionPerformed(evt);
            }
        });

        printcombo2.setText("Refresh");
        printcombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printcombo2ActionPerformed(evt);
            }
        });

        jComboBox3Currency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3CurrencyActionPerformed(evt);
            }
        });

        printcombo3.setText("Refresh");
        printcombo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printcombo3ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ShowAsset);

        javax.swing.GroupLayout graphPanelLayout = new javax.swing.GroupLayout(graphPanel);
        graphPanel.setLayout(graphPanelLayout);
        graphPanelLayout.setHorizontalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        graphPanelLayout.setVerticalGroup(
            graphPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        listOfAssets.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Select assets" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listOfAssets);

        creatgraphbutton.setText("Create Graph");
        creatgraphbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creatgraphbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1Stock, 0, 134, Short.MAX_VALUE)
                            .addComponent(jComboBox2Commodity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox3Currency, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(printcombo2)
                            .addComponent(printcombo1)
                            .addComponent(printcombo3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(creatgraphbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap(106, Short.MAX_VALUE))
                    .addComponent(graphPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(creatgraphbutton))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printcombo1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2Commodity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printcombo2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox3Currency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(printcombo3)))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tabGeneralText.addTab("Assets & Graph", jPanel2);

        jLabel2.setText("Pick the company and buy out half of assets.");

        jComboBox1Company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1CompanyActionPerformed(evt);
            }
        });

        beforeCompany.setColumns(20);
        beforeCompany.setRows(5);
        jScrollPane4.setViewportView(beforeCompany);

        afterCompany.setColumns(20);
        afterCompany.setRows(5);
        jScrollPane5.setViewportView(afterCompany);

        noStocktoBuyOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noStocktoBuyOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4)
                    .addComponent(jComboBox1Company, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(noStocktoBuyOut, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1Company, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(noStocktoBuyOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel3.setText("Take a look at the Company");

        jComboBox1Company1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1Company1ActionPerformed(evt);
            }
        });

        areaForCompany.setColumns(20);
        areaForCompany.setRows(5);
        jScrollPane6.setViewportView(areaForCompany);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1Company1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1Company1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6)
                .addContainerGap())
        );

        jLabel12.setText("Take a look at the Investor");

        jComboBox1Investor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1InvestorActionPerformed(evt);
            }
        });

        jTextAreaInvestor.setColumns(20);
        jTextAreaInvestor.setRows(5);
        jScrollPane8.setViewportView(jTextAreaInvestor);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1Investor, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1Investor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tabGeneralText.addTab("Company & Investor", jPanel3);

        getContentPane().add(tabGeneralText, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1Company1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1Company1ActionPerformed
        // TODO add your handling code here:
        Company myCompany =MainWorld.listOfCompanies.get(jComboBox1Company1.getSelectedIndex());
        areaForCompany.setText(myCompany.describe());
    }//GEN-LAST:event_jComboBox1Company1ActionPerformed

    private void noStocktoBuyOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noStocktoBuyOutActionPerformed
        // TODO add your handling code here:
        synchronized(myChoosenCompany.getCompanyStock().getMonitorAsset()){

            int number = noStocktoBuyOut.getSelectedIndex();
            myChoosenCompany.buyOwnStocks(Math.round(number));
            afterCompany.setText(myChoosenCompany.describe());
        }
    }//GEN-LAST:event_noStocktoBuyOutActionPerformed

    private void jComboBox1CompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1CompanyActionPerformed
        // TODO add your handling code here:
        myChoosenCompany = (Company) MainWorld.listOfCompanies.get(jComboBox1Company.getSelectedIndex());
        synchronized(myChoosenCompany.getCompanyStock().getMonitorAsset()){
            beforeCompany.setText(myChoosenCompany.describe());
            for (int i = 0;i<myChoosenCompany.getCompanyStock().getQuantity();i++){
                noStocktoBuyOut.addItem(Integer.toString(i));
            }
        }
    }//GEN-LAST:event_jComboBox1CompanyActionPerformed
        private XYDataset dataset;

    private void speedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speedMouseClicked
        // TODO add your handling code here:
        freq.setText("Your Traders trade every "+ Float.toString((float) speed.getValue()/1000) + " seconds.");
        MainWorld.speed=speed.getValue();
    }//GEN-LAST:event_speedMouseClicked

    private void speedMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speedMouseDragged
        freq.setText("Your Traders trade every "+ Float.toString((float) speed.getValue()/1000) + " seconds.");
        MainWorld.speed=speed.getValue();
    }//GEN-LAST:event_speedMouseDragged

    private void dodComMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodComMActionPerformed
        // TODO add your handling code here:
        MainWorld.createCommodityMarkets(1);
        nComM.setText(Integer.toString(MainWorld.noCommodityMarkets));
        textPanelCreateSection.setText(MainWorld.listOfMarkets.get(MainWorld.listOfMarkets.size()-1).describe());
        nInv.setText(Integer.toString(MainWorld.noInvestor));
         int i =MainWorld.listOfTraders.size()-1;
        jComboBox1Investor.addItem(MainWorld.listOfTraders.get(i).getFirstName());
        i =MainWorld.listOfTraders.size()-2;
        jComboBox1Investor.addItem(MainWorld.listOfTraders.get(i).getFirstName());
    }//GEN-LAST:event_dodComMActionPerformed

    private void dodFundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodFundActionPerformed
        // TODO add your handling code here:
        //        MainWorld.createF(1);
        nFund.setText("No Fund implemented, sorry...");
    }//GEN-LAST:event_dodFundActionPerformed

    private void dodInvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodInvActionPerformed
        // TODO add your handling code here:
        MainWorld.createInvestors(1);
        nInv.setText(Integer.toString(MainWorld.noInvestor));
        textPanelCreateSection.setText(((Investor)MainWorld.listOfTraders.get(MainWorld.listOfTraders.size()-1)).describe());
        int i =MainWorld.listOfTraders.size()-1;
        jComboBox1Investor.addItem(MainWorld.listOfTraders.get(i).getFirstName());
     

    }//GEN-LAST:event_dodInvActionPerformed

    private void dodCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodCompanyActionPerformed
        // TODO add your handling code here:
        MainWorld.createCompanies(1);
        nStock.setText(Integer.toString(MainWorld.noCompany));
        nCompany.setText(Integer.toString(MainWorld.noCompany));
        textPanelCreateSection.setText(MainWorld.listOfCompanies.get(MainWorld.listOfCompanies.size()-1).describe());
        listModel.addElement(MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1).getName());
        this.listOfAssets.setModel( listModel );
        jComboBox1Company.addItem(MainWorld.listOfCompanies.get(MainWorld.listOfCompanies.size()-1).getName());
        jComboBox1Company1.addItem(MainWorld.listOfCompanies.get(MainWorld.listOfCompanies.size()-1).getName());
    }//GEN-LAST:event_dodCompanyActionPerformed

    private void dodIndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodIndActionPerformed
        MainWorld.createIndexes(1);
        nInd.setText(Integer.toString(MainWorld.noIndex));
        textPanelCreateSection.setText(MainWorld.listOfIndexes.get(MainWorld.listOfIndexes.size()-1).describe());
        if (MainWorld.listOfIndexes.size()==GeneratingThings.cathegories.length){
            textPanelCreateSection.setText("Sorry, but you can't add any more indexes. \nYou have reached the maximum number of indexes: "+
                + MainWorld.listOfIndexes.size());
        }
    }//GEN-LAST:event_dodIndActionPerformed

    private void dodCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodCurActionPerformed
        // TODO add your handling code here:
        MainWorld.createCurrencies(1);
        nCur.setText(Integer.toString(MainWorld.noCurrency));
        jComboBox3Currency.addItem(MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1).getName());
        textPanelCreateSection.setText( ((Currency) MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1)).describe() );
        listModel.addElement(MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1).getName());
        this.listOfAssets.setModel( listModel );
    }//GEN-LAST:event_dodCurActionPerformed

    private void dodComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodComActionPerformed
        MainWorld.createCommodities(1);
        nCom.setText(Integer.toString(MainWorld.noCommodity));
        jComboBox2Commodity.addItem(MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1).getName());
        textPanelCreateSection.setText( ((Commodity) MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1)).describe() );
        listModel.addElement(MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1).getName());
        this.listOfAssets.setModel( listModel );
    }//GEN-LAST:event_dodComActionPerformed

    private void dodStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodStockActionPerformed
        // TODO add your handling code here:
        MainWorld.createCompanies(1);
        nStock.setText(Integer.toString(MainWorld.noCompany));
        nCompany.setText(Integer.toString(MainWorld.noCompany));
        jComboBox1Stock.addItem(MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1).getName());
        textPanelCreateSection.setText( ((Stock) MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1)).describe() );
        listModel.addElement(MainWorld.listOfAssets.get(MainWorld.listOfAssets.size()-1).getName());
        this.listOfAssets.setModel( listModel );
        jComboBox1Company.addItem(MainWorld.listOfCompanies.get(MainWorld.listOfCompanies.size()-1).getName());
        jComboBox1Company1.addItem(MainWorld.listOfCompanies.get(MainWorld.listOfCompanies.size()-1).getName());
    }//GEN-LAST:event_dodStockActionPerformed

    private void dodCurMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dodCurMActionPerformed
        // TODO add your handling code here:
        MainWorld.createCurrencyMarkets(1);
        nCurM.setText(Integer.toString(MainWorld.noCurrencyMarkets));
        textPanelCreateSection.setText(MainWorld.listOfMarkets.get(MainWorld.listOfMarkets.size()-1).describe() );
        nInv.setText(Integer.toString(MainWorld.noInvestor));
        int i =MainWorld.listOfTraders.size()-1;
        jComboBox1Investor.addItem(MainWorld.listOfTraders.get(i).getFirstName());
        i =MainWorld.listOfTraders.size()-2;
        jComboBox1Investor.addItem(MainWorld.listOfTraders.get(i).getFirstName());
    }//GEN-LAST:event_dodCurMActionPerformed

    private void dStockMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dStockMActionPerformed
        // TODO add your handling code here:
        MainWorld.createStockMarkets(1);
        nStockM.setText(Integer.toString(MainWorld.noStockMarkets));
        nInv.setText(Integer.toString(MainWorld.noInvestor));

        textPanelCreateSection.setText(MainWorld.listOfMarkets.get(MainWorld.listOfMarkets.size()-1).describe() );
         int i =MainWorld.listOfTraders.size()-1;
        jComboBox1Investor.addItem(MainWorld.listOfTraders.get(i).getFirstName());
        i =MainWorld.listOfTraders.size()-2;
        jComboBox1Investor.addItem(MainWorld.listOfTraders.get(i).getFirstName());
    }//GEN-LAST:event_dStockMActionPerformed

    private void jComboBox1InvestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1InvestorActionPerformed
        // TODO add your handling code here:
        jTextAreaInvestor.setText( ((Investor) MainWorld.listOfTraders.get(jComboBox1Investor.getSelectedIndex())).describe());
        
    }//GEN-LAST:event_jComboBox1InvestorActionPerformed

    private void creatgraphbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creatgraphbuttonActionPerformed
        // TODO add your handling code here:
        graphPanel.setLayout(null);
        graphPanel.revalidate();
        TimeSeriesCollection tsc = new TimeSeriesCollection();
        String name="";
        for (int i = 0; i<listOfAssets.getSelectedIndices().length;i++){

            tsc.addSeries( MainWorld.listOfAssets.get( listOfAssets.getSelectedIndices()[i] ).getSeries());
            name =name + MainWorld.listOfAssets.get(listOfAssets.getSelectedIndices()[i] ).getName()+" & ";
        }
        this.dataset= tsc;
        JFreeChart chart = ChartFactory.createTimeSeriesChart(name,  "Time",    "Price",dataset, false ,false,false);
        graphPanel.setLayout(new java.awt.BorderLayout());
        ChartPanel CP = new ChartPanel(chart);
        graphPanel.add(CP,BorderLayout.CENTER);
        graphPanel.validate();
        ////////////////////////////
        final Graph demo = new Graph( name,listOfAssets.getSelectedIndices() );
        demo.pack( );
        RefineryUtilities.positionFrameRandomly( demo );
        demo.setVisible( true );
    }//GEN-LAST:event_creatgraphbuttonActionPerformed

    private void printcombo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printcombo3ActionPerformed
        Currency myStock=(Currency) hashMapAsset.get(jComboBox3Currency.getSelectedItem());
        ShowAsset.setText(myStock.describe());
    }//GEN-LAST:event_printcombo3ActionPerformed

    private void jComboBox3CurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3CurrencyActionPerformed
        // TODO add your handling code here:
        Currency myStock=(Currency) hashMapAsset.get(jComboBox3Currency.getSelectedItem());
        ShowAsset.setText(myStock.describe());
    }//GEN-LAST:event_jComboBox3CurrencyActionPerformed

    private void printcombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printcombo2ActionPerformed
        // TODO add your handling code here:
        Commodity myStock=(Commodity) hashMapAsset.get(jComboBox2Commodity.getSelectedItem());
        ShowAsset.setText(myStock.describe());
    }//GEN-LAST:event_printcombo2ActionPerformed

    private void jComboBox2CommodityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2CommodityActionPerformed
        // TODO add your handling code here:
        Commodity myStock=(Commodity) hashMapAsset.get(jComboBox2Commodity.getSelectedItem());
        ShowAsset.setText(myStock.describe());
    }//GEN-LAST:event_jComboBox2CommodityActionPerformed

    private void printcombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printcombo1ActionPerformed
        // TODO add your handling code here:
        Stock myStock=(Stock) hashMapAsset.get(jComboBox1Stock.getSelectedItem());
        ShowAsset.setText(myStock.describe());
    }//GEN-LAST:event_printcombo1ActionPerformed

    private void jComboBox1StockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1StockActionPerformed
        // TODO add your handling code here:
        Stock myStock=(Stock) hashMapAsset.get(jComboBox1Stock.getSelectedItem());
        ShowAsset.setText(myStock.describe());
    }//GEN-LAST:event_jComboBox1StockActionPerformed
     Company myChoosenCompany;    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane ShowAsset;
    private javax.swing.JTextArea afterCompany;
    private javax.swing.JTextArea areaForCompany;
    private javax.swing.JTextArea beforeCompany;
    private javax.swing.JButton creatgraphbutton;
    private javax.swing.JButton dStockM;
    private javax.swing.JButton dodCom;
    private javax.swing.JButton dodComM;
    private javax.swing.JButton dodCompany;
    private javax.swing.JButton dodCur;
    private javax.swing.JButton dodCurM;
    private javax.swing.JButton dodFund;
    private javax.swing.JButton dodInd;
    private javax.swing.JButton dodInv;
    private javax.swing.JButton dodStock;
    private javax.swing.JLabel freq;
    private javax.swing.JPanel graphPanel;
    private javax.swing.JComboBox<String> jComboBox1Company;
    private javax.swing.JComboBox<String> jComboBox1Company1;
    public static javax.swing.JComboBox<String> jComboBox1Investor;
    private javax.swing.JComboBox<String> jComboBox1Stock;
    private javax.swing.JComboBox<String> jComboBox2Commodity;
    private javax.swing.JComboBox<String> jComboBox3Currency;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jTextAreaInvestor;
    private javax.swing.JList<String> listOfAssets;
    private javax.swing.JLabel nCom;
    private javax.swing.JLabel nComM;
    private javax.swing.JLabel nCompany;
    private javax.swing.JLabel nCur;
    private javax.swing.JLabel nCurM;
    private javax.swing.JLabel nFund;
    private javax.swing.JLabel nInd;
    private javax.swing.JLabel nInv;
    private javax.swing.JLabel nStock;
    private javax.swing.JLabel nStockM;
    private javax.swing.JComboBox<String> noStocktoBuyOut;
    private javax.swing.JButton printcombo1;
    private javax.swing.JButton printcombo2;
    private javax.swing.JButton printcombo3;
    private javax.swing.JSlider speed;
    private javax.swing.JTabbedPane tabGeneralText;
    private javax.swing.JTextPane textPanelCreateSection;
    // End of variables declaration//GEN-END:variables
}
